version: '3.8'

services:
  blur-detection:
    build: .
    container_name: bulk-blur-detection
    volumes:
      - /mnt:/app/images  # Mount a local folder for images (optional)
    ports:
      - "5050:5000"  # Expose the web app on port 5050
    environment:
      - FLASK_ENV=development
